SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE FROM MEMBER;

INSERT INTO MEMBER(NAME, USERID, PWD, EMAIL, PHONE, ADMIN) VALUES ('박규영', 'parkgy', '1234', 'pgy@naver.com', '010-1111-2222', 0);

-- login
SELECT NAME, USERID, EMAIL, PHONE, ADMIN, JOINDATE FROM MEMBER WHERE USERID = 'somi' AND pwd = '1234';

UPDATE MEMBER
   SET NAME = '문채원', PWD ='5678', EMAIL='mcw@gmail.com',
       PHONE='010-3333-5555', ADMIN=1, JOINDATE='2020-08-20' WHERE USERID = 'parkgy';
 
DELETE FROM MEMBER WHERE USERID = 'parkgy';

-- usercheck
SELECT PWD FROM MEMBER WHERE USERID = 'somi';

-- title
SELECT TITLE_NO, TITLE_NAME FROM TITLE ORDER BY TITLE_NO;

SELECT MAX(TITLE_NO)+1 FROM TITLE;

-- dept
SELECT DEPT_NO, DEPT_NAME, FLOOR FROM DEPARTMENT ORDER BY DEPT_NO;

INSERT INTO DEPARTMENT VALUES(5, '인사', 5);

UPDATE DEPARTMENT SET DEPT_NAME = '운영', FLOOR = 6 WHERE DEPT_NO = 5;

DELETE FROM DEPARTMENT WHERE DEPT_NO = 5;

SELECT MAX(DEPT_NO)+1 FROM DEPARTMENT;

SELECT DEPT_NO, DEPT_NAME, FLOOR FROM DEPARTMENT WHERE DEPT_NO = 1;

-- emp
SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO FROM EMPLOYEE;
